// Central knute-library seed content (ADR-0014). Source of truth: docs/library-seed-source.md
// (Stavanger russ knutebok — transcribed + verified 2026-06-18. App Store content
// cleanup 2026-07-24 removed 75 entries incl. the whole Sex + Alkohol folders,
// approved by Ludvig — see docs/app-store-content-review.md. 111 knuter remain.)
// Defaults applied at seed time: evidenceType 'media', minAge 17, region null (Nasjonalt).
// Only the exceptions are spelled out per entry.
export type LibraryFolder = 'Generelle' | 'Dobbel' | 'Rampestrek' | 'Alkohol' | 'Sex'

export type LibrarySeedKnute = {
  title: string
  points: number
  folder: LibraryFolder
  description: string
  evidenceType?: 'text' // default 'media'
  minAge?: 18 // default 17
  region?: string // default null = Nasjonalt
}

export const librarySeedKnuter: LibrarySeedKnute[] = [
  // Generelle
  { title: 'BI', points: 28, folder: 'Generelle', description: 'Vipps økonomisjefen i russestyret 10 kr.' },
  { title: 'Romeo', points: 10, folder: 'Generelle', description: 'Skriv et romantisk dikt til loveboss og les det opp.' },
  { title: 'Bikkjå', points: 10, folder: 'Generelle', description: 'Bjeff høyt minst 10 ganger i løpet av én skoletime.' },
  { title: 'Lættis Alarm', points: 12, folder: 'Generelle', description: 'Få en knutesjef til å le høyt.' },
  { title: 'Walk of Shame', points: 12, folder: 'Generelle', description: 'Møt på skolen rett fra rulling, uten å dra hjem først.' },
  { title: 'Fritzel', points: 12, folder: 'Generelle', description: 'Ikke bli «cheatet på» (lurt) av noen gjennom hele russetiden.' },
  { title: 'Veldedighet', points: 12, folder: 'Generelle', description: 'Vipps et valgfritt beløp til Kreftforeningen.' },
  { title: 'Jævla geek', points: 13, folder: 'Generelle', description: 'Les en hel bok i løpet av russetiden.' },
  { title: 'Jafs', points: 13, folder: 'Generelle', description: 'Spis en hel cheeseburger i én jafs.' },
  { title: 'Legesjekken', points: 12, folder: 'Generelle', description: 'Få russelegen til å ta en full helsesjekk av deg.' },
  { title: 'Klam', points: 15, folder: 'Generelle', description: 'Gjennomfør en hel kroppsøvingstime iført russedress.' },
  { title: 'Teams', points: 15, folder: 'Generelle', description: 'Ring læreren på Teams midt i timen og spør om du kan delta digitalt.' },
  { title: 'Ville vesten', points: 15, folder: 'Generelle', description: 'Kjøp en rosa russelue av en annen russ.' },
  { title: 'Hosten', points: 15, folder: 'Generelle', description: 'Host fram et «vors» eller «narsj» høyt.' },
  { title: 'Konduktør', points: 18, folder: 'Generelle', description: 'Delta i russetoget.' },
  { title: 'Up Syndrom', points: 18, folder: 'Generelle', description: 'Kjøp og spis to is i løpet av én skoletime.' },
  { title: 'Company', points: 18, folder: 'Generelle', description: 'Sitt sammen med en Vg1- eller Vg2-elev en hel lunsjpause.' },
  { title: 'Tixern', points: 18, folder: 'Generelle', description: 'Syng «Sjeiken» høyt i kantina.' },
  { title: 'Morgenstund', points: 18, folder: 'Generelle', description: 'Ta et morgenbad (bad i sjø/vann tidlig på dagen).' },
  { title: 'Bomullsklump', points: 20, folder: 'Generelle', description: 'Ta vaksinen mot hjernehinnebetennelse.' },
  { title: 'Vinter OL', points: 20, folder: 'Generelle', description: 'Dra til Vinmonopolet på rulleski, skøyter eller ski.' },
  { title: 'Bursdagen', points: 20, folder: 'Generelle', description: 'Feir bursdagen til en lærer som ikke har bursdag.' },
  { title: 'Badenymfen', points: 22, folder: 'Generelle', description: 'Bad i Breiavatnet.', region: 'Stavanger' },
  { title: 'Karl Johan', points: 22, folder: 'Generelle', description: 'Spør 20 tilfeldige på gata om «kiss or slap».' },
  { title: 'Vikaren', points: 22, folder: 'Generelle', description: 'Delta aktivt i undervisningen til en førsteklasse, som om du går der.' },
  { title: 'Testen', points: 25, folder: 'Generelle', description: 'Test deg for kjønnssykdommer.' },
  { title: 'Wing Man', points: 25, folder: 'Generelle', description: 'Gi nummeret til en medruss sin mor til knutesjefene.' },
  { title: 'Godt Å Blandet', points: 25, folder: 'Generelle', description: 'Gå på date med noen fra innføringsklassen.' },
  { title: 'Your final challenge', points: 25, folder: 'Generelle', description: 'La noen andre gå fritt gjennom telefonen din.' },
  { title: 'Linselus', points: 25, folder: 'Generelle', description: 'Ta minst 20 selfier på telefonen til en lærer.' },
  { title: 'Tvillingen', points: 25, folder: 'Generelle', description: 'Knytt deg fysisk sammen med en medelev og hold sammen en hel skoledag.' },
  { title: 'Bøsså', points: 25, folder: 'Generelle', description: 'Vær bøssebærer for en innsamlingsaksjon.' },
  { title: 'Russelue', points: 30, folder: 'Generelle', description: 'Gjennomfør russedåp sammen med en medruss.' },
  { title: 'Daten', points: 35, folder: 'Generelle', description: '«Kidnapp» russepresidenten og ta hen med på en overraskelsesmiddag.' },
  { title: 'Nørd', points: 35, folder: 'Generelle', description: 'Få karakteren 6 på minst to vurderinger i løpet av russetiden.' },
  { title: 'Barfot fredag', points: 35, folder: 'Generelle', description: 'Gå barfot hver fredag gjennom hele russetiden (obligatorisk).' },
  { title: 'Vaske Instruksen', points: 38, folder: 'Generelle', description: 'Gå hele russetiden uten å vaske russedressen.' },
  { title: 'Handcuff', points: 40, folder: 'Generelle', description: 'Lenk deg fast til noen en hel skoledag.' },
  { title: 'Rim', points: 45, folder: 'Generelle', description: 'Hold en hel presentasjon på rim.' },
  { title: 'Turisten', points: 45, folder: 'Generelle', description: 'Gå til Preikestolen iført russedress.', region: 'Stavanger' },
  { title: 'Trofast', points: 45, folder: 'Generelle', description: 'Vær trofast mot partneren din gjennom hele russetiden.' },
  { title: 'Gullungen', points: 48, folder: 'Generelle', description: 'Ikke ta narkotika gjennom hele russetiden.' },
  { title: 'Årets Ørekreft', points: 50, folder: 'Generelle', description: 'Fremfør årets hjemmesnekk (russelåt) i kantina.' },
  { title: 'Mukbang', points: 83, folder: 'Generelle', description: 'Spis 54 nuggets i løpet av én studietime.' },
  // Dobbel
  { title: 'Bronsetråd', points: 25, folder: 'Dobbel', description: 'Gjennomfør 5 knuter innen 24 timer.' },
  { title: 'Skuespill', points: 25, folder: 'Dobbel', description: 'Fremfør et skuespill i kantina i minst 5 minutter.' },
  { title: 'Stjerne', points: 25, folder: 'Dobbel', description: 'Ha en Just Dance-økt i kantina.' },
  { title: 'Michelin', points: 25, folder: 'Dobbel', description: 'Spis et varmt måltid med tallerken og bestikk, i finklær, på skolen.' },
  { title: 'Sing a Long', points: 25, folder: 'Dobbel', description: 'Start allsang i kantina.' },
  { title: 'Boomboxen', points: 28, folder: 'Dobbel', description: 'Gjem en høyttaler i sekken til en medelev og spill av musikk i undervisningen.' },
  { title: 'Counting or not counting', points: 30, folder: 'Dobbel', description: 'Vinn en debatt mot Gunnar.' },
  { title: 'Travis Scott', points: 30, folder: 'Dobbel', description: 'Hold en rapbattle i skolegården.' },
  { title: 'Foodnite', points: 30, folder: 'Dobbel', description: 'Start en matkrig i kantina.' },
  { title: 'Livstiden', points: 30, folder: 'Dobbel', description: 'Start en vannkrig i kantina.' },
  { title: 'Sommerkroppen', points: 35, folder: 'Dobbel', description: 'Fullfør en treningsøkt i kantina på minst 15 minutter.' },
  { title: 'St. Monsen', points: 35, folder: 'Dobbel', description: 'Overnatt i hagen til en lærer.' },
  { title: 'Earlybird', points: 35, folder: 'Dobbel', description: 'Overnatt på skolens område.' },
  { title: 'Komikeren', points: 40, folder: 'Dobbel', description: 'Hold standup i kantina og få minst 5 latere.' },
  { title: 'Rævsleiker', points: 42, folder: 'Dobbel', description: 'Få signaturen til alle lærerne dine på russedressen.' },
  { title: 'Stjerneelev / Presis', points: 45, folder: 'Dobbel', description: 'Ha null fravær gjennom hele russetiden.' },
  { title: 'Sølvtråd', points: 45, folder: 'Dobbel', description: 'Gjennomfør 15 knuter innen 24 timer.' },
  { title: 'Māthi hiyi ahh haircut', points: 50, folder: 'Dobbel', description: 'Bli skamklipt på skolen i løpet av russetiden.' },
  { title: 'Flyplass', points: 65, folder: 'Dobbel', description: 'Bruk en koffert som skolesekk en hel uke.' },
  { title: 'Kong Lættis', points: 70, folder: 'Dobbel', description: 'Hold standup i en kinosal de siste 5 minuttene før filmen starter.' },
  { title: 'Edru Russ', points: 82, folder: 'Dobbel', description: 'Vær edru gjennom hele russetiden.' },
  { title: 'Gulltråd', points: 80, folder: 'Dobbel', description: 'Gjennomfør 40 knuter innen 24 timer.' },
  { title: 'Føderen', points: 100, folder: 'Dobbel', description: 'Fød under russetiden.' },
  // Rampestrek
  { title: 'Uno Reverse', points: 10, folder: 'Rampestrek', description: 'Få et russekort av en unge, i stedet for å gi bort ditt.' },
  { title: 'Penis Leken', points: 12, folder: 'Rampestrek', description: 'Ha «penis-leken» (si «penis» stadig høyere) gjennom en hel time.' },
  { title: 'Bondeknøl', points: 12, folder: 'Rampestrek', description: 'Gå uten russesleik en hel dag.' },
  { title: 'Kverulanten', points: 12, folder: 'Rampestrek', description: 'Prut på prisen på øl i butikken.' },
  { title: 'Plukk opp!', points: 12, folder: 'Rampestrek', description: 'Rydd i kantina, eller hjelp til med opprydding etter russedåpen.' },
  { title: 'Jonnern', points: 15, folder: 'Rampestrek', description: 'Overbevis en fremmed om at de kjenner deg.' },
  { title: 'Dørvakten', points: 15, folder: 'Rampestrek', description: 'Ta betalt for å åpne døra ut av butikken for folk.' },
  { title: 'Baka', points: 15, folder: 'Rampestrek', description: 'Rop «baka» for full hals i kantina.' },
  { title: 'Kiss or Slap', points: 15, folder: 'Rampestrek', description: 'Spør en knutesjef om «kiss or slap».' },
  { title: 'Kjølevare', points: 15, folder: 'Rampestrek', description: 'Frys skoen til noen på fest.' },
  { title: 'Sladrehalsen', points: 15, folder: 'Rampestrek', description: 'Sladre på en mindreårig som er på et utested.' },
  { title: 'Spaneren', points: 18, folder: 'Rampestrek', description: 'Oppfør deg mistenkelig like utenfor politistasjonen.' },
  { title: 'Kødd', points: 18, folder: 'Rampestrek', description: 'Vær «kødden» (tøysete på gøy) en hel dag.' },
  { title: 'Lættis banan', points: 18, folder: 'Rampestrek', description: 'Spis 3 bananer i løpet av en presentasjon.' },
  { title: 'Dør ringeren', points: 18, folder: 'Rampestrek', description: 'Ring på døra hos noen og bli stående uten å flytte deg før de lukker.' },
  { title: 'Underpult', points: 18, folder: 'Rampestrek', description: 'Sitt under pulten din en hel skoletime.' },
  { title: 'LSSP', points: 18, folder: 'Rampestrek', description: 'Stjel sokkene til noen i løpet av russetiden.' },
  { title: 'Klagemuren', points: 18, folder: 'Rampestrek', description: 'Be høyt til «Big Yahu» under en eksamen.' },
  { title: 'Ave Maria', points: 18, folder: 'Rampestrek', description: 'Fortell en synd til en av prestene.' },
  { title: 'Overpult', points: 20, folder: 'Rampestrek', description: 'Sitt oppå pulten din en hel skoletime.' },
  { title: 'Gjensitting', points: 20, folder: 'Rampestrek', description: 'Rop «hold kjeft» til en lærer.' },
  { title: 'Vrangen', points: 22, folder: 'Rampestrek', description: 'Gå med alle klærne på vrangen en hel skoledag.' },
  { title: 'Dehydrert', points: 22, folder: 'Rampestrek', description: 'Stå ved vannkranen og nekt andre å fylle vann et helt friminutt.' },
  { title: 'Slalåmbakken', points: 22, folder: 'Rampestrek', description: 'Ak ned trappene i kantina.' },
  { title: 'Horndog', points: 22, folder: 'Rampestrek', description: 'Kjøp kondomer i butikken kun ved hjelp av kroppsspråk.' },
  { title: 'Brage Spesial', points: 25, folder: 'Rampestrek', description: 'Ring 1881 og spør om «benløs bæsjepizza». Samtalen må filmes.' },
  { title: 'Parasitt', points: 25, folder: 'Rampestrek', description: 'Sov hjemme hos en medruss uten at de vet det, og vekk dem med frokost.' },
  { title: 'Diktatoren', points: 25, folder: 'Rampestrek', description: 'Stå køvakt i kantina iført refleksvest og briller.' },
  { title: 'Footlong', points: 25, folder: 'Rampestrek', description: 'Bruk brød som sko en hel skoledag.' },
  { title: 'Sexed', points: 25, folder: 'Rampestrek', description: 'Hold «seksualundervisning» i kantina.' },
  { title: 'Shimmamonsteret', points: 28, folder: 'Rampestrek', description: 'Gaffateip en tannkost til hostens familie på fest.' },
  { title: 'Nei', points: 28, folder: 'Rampestrek', description: 'Si nei til alt en hel dag.' },
  { title: 'Kjeft', points: 28, folder: 'Rampestrek', description: 'Kjeft på statuen av Alexander Kielland i 1 minutt.', region: 'Stavanger' },
  { title: 'Propellen', points: 30, folder: 'Rampestrek', description: 'Spring gjennom skolegården til en barneskole i et friminutt, uten å dele ut russekort.' },
  { title: 'Gave', points: 30, folder: 'Rampestrek', description: 'Surr inn bilen til en lærer med dorull.' },
  { title: 'Sigma', points: 30, folder: 'Rampestrek', description: 'Gå med russesleik gjennom hele russetiden.' },
  { title: 'Penis', points: 32, folder: 'Rampestrek', description: 'Tegn peniser på tavla i 10 forskjellige klasserom.' },
  { title: 'Jim Carrey', points: 32, folder: 'Rampestrek', description: 'Si ja til alt en hel dag.' },
  { title: 'Smiskeren', points: 35, folder: 'Rampestrek', description: 'Få et kyss på kinnet av en lærer.' },
  { title: 'Ikea', points: 45, folder: 'Rampestrek', description: 'Lek «hjemmeleken» på IKEA med minst 10 personer.' },
  { title: 'Supermann', points: 45, folder: 'Rampestrek', description: 'Gå en hel dag med undertøyet utenpå russedressen.' },
  { title: 'Olsenbanden', points: 50, folder: 'Rampestrek', description: 'Finn på en rampestrek og vis den til en knutesjef for godkjenning.' },
  { title: 'Vågen', points: 50, folder: 'Rampestrek', description: 'Lat som du er hund inne i en butikk og bjeff på en ansatt.' },
  { title: 'Sjarmøren', points: 25, folder: 'Rampestrek', description: 'Flørt åpenlyst med en lærer gjennom en hel time.' },
]
